prod

diff --git a/.github/workflows/production-deploy.yml b/.github/workflows/production-deploy.yml
--- a/.github/workflows/production-deploy.yml
+++ b/.github/workflows/production-deploy.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
       - master
-  workflow_dispatch: 
+  workflow_dispatch:
 
 jobs:
   list-lbs:
@@ -19,16 +19,24 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1  # Možeš postaviti bilo koji region, nije bitno jer ćemo kasnije menjati region
+          aws-region: us-east-1
+
+      - name: Get AWS Regions
+        id: get-regions
+        run: |
+          regions=$(aws ec2 describe-regions --query "Regions[].RegionName" --output text)
+          echo "Found AWS regions: $regions"
+          echo "REGIONS=$regions" >> $GITHUB_ENV
 
       - name: List Active Load Balancers across US regions
         run: |
-          regions=("us-east-1" "us-east-2" "us-west-1" "us-west-2" "us-central-1" "us-west-3")
-
-          for region in "${regions[@]}"; do
+          for region in $REGIONS; do
             echo "Listing active Load Balancers in region: $region"
-            
-            aws elbv2 describe-load-balancers --region $region --output json | jq -r \
-              '.LoadBalancers[] | select(.State.Code == "active") | .LoadBalancerArn'
+            load_balancers=$(aws elbv2 describe-load-balancers --region $region --output json)
+            if [ $? -ne 0 ]; then
+              echo "AWS CLI command failed in region $region"
+              exit 1
+            fi
+            echo "$load_balancers" | jq -r '.LoadBalancers[] | select(.State.Code == "active") | .LoadBalancerArn'
           done
 
